### PR TITLE
Add missing layout for EspressoBin v5 DDR3 2CS 2GB board

### PR DESCRIPTION
**Pull request by dhewg**
The 2GB variant shipped as part of the original KickStarter campaign.

@kostapr this topology is just missing, armbian uses it too.

Compared to topo 2:
````
diff -u tim/ddr/DDR_TOPOLOGY_2.txt tim/ddr/DDR_TOPOLOGY_7.txt 
--- tim/ddr/DDR_TOPOLOGY_2.txt	2020-09-01 09:23:19.051917361 +0200
+++ tim/ddr/DDR_TOPOLOGY_7.txt	2020-09-01 10:07:01.176566368 +0200
@@ -3,7 +3,7 @@
 # each item is one parameter for DDR topology, which will be parsed by
 # DDR tool and generate DDR register list accordingly.
 # Supported Marvell boards:
-#       DDR3 2CS : EspressoBIN (1GB)
+#       DDR3 2CS : EspressoBIN (2GB)
 #
 
 #DDR3
@@ -18,5 +18,5 @@
 #16BIT
 ddr_bus_width_index=2
 
-#4Gbits (512MB)
-ddr_mem_size_index=3
+#8Gbits (1GB)
+ddr_mem_size_index=4

````

### CODE REVIEW

**Comment by dhewg** [comment]
This is basically #5 for the proper branch with the next free topo number. If merged #5 can be closed too.

**Review by kostapr — APPROVED** [review]

**Comment by dhewg** [comment]
Thanks!

**Comment by pali** [comment]
@dhewg: Can you send pull request for updating `DDR_TOPOLOGY` documentation for ATF? Currently there are documented only values 0-6: https://trustedfirmware-a.readthedocs.io/en/latest/plat/marvell/armada/build.html

@kostapr: I think that now PR #5 could be closed as this merged PR replaced it.

**Comment by pali** [comment]
> @dhewg: Can you send pull request for updating `DDR_TOPOLOGY` documentation for ATF? Currently there are documented only values 0-6: https://trustedfirmware-a.readthedocs.io/en/latest/plat/marvell/armada/build.html

I did it: https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/6248

**Comment by dhewg** [comment]
Thanks, I fixed it locally but forgot to send it upstream ;)
Here's my diff, which also adds comments about 1gb 1/2cs variants:
```
diff --git a/docs/plat/marvell/armada/build.rst b/docs/plat/marvell/armada/build.rst
index 6b9054c7c..1e3eabd95 100644
--- a/docs/plat/marvell/armada/build.rst
+++ b/docs/plat/marvell/armada/build.rst
@@ -124,11 +124,12 @@ There are several build options:
         Supported Options:
             - DDR3 1CS (0): DB-88F3720-DDR3-Modular (512MB); EspressoBIN (512MB)
             - DDR4 1CS (1): DB-88F3720-DDR4-Modular (512MB)
-            - DDR3 2CS (2): EspressoBIN V3-V5 (1GB)
+            - DDR3 2CS (2): EspressoBIN V3-V5 (1GB 2CS)
             - DDR4 2CS (3): DB-88F3720-DDR4-Modular (4GB)
-            - DDR3 1CS (4): DB-88F3720-DDR3-Modular (1GB)
+            - DDR3 1CS (4): DB-88F3720-DDR3-Modular (1GB); EspressoBIN V3-V5 (1GB 1CS)
             - DDR4 1CS (5): EspressoBin V7 (1GB)
             - DDR4 2CS (6): EspressoBin V7 (2GB)
+            - DDR3 2CS (7): EspressoBIN V3-V5 (2GB)
             - CUSTOMER (CUST): Customer board, DDR3 1CS 512MB
 
 - CLOCKSPRESET

```

**Comment by pali** [comment]
Ok, I updated it.

**Pull request merged**
