### PR TITLE
ddr: Add topology for ESPRESSObin 2 GB

### PR DESCRIPTION
**Pull request by afaerber**
Super EspressoBin apparently uses 2x 1 GB DDR3.

Grab the next free DDR topology number, adjust the buildtim.sh script to
cope with the new topology number and derive a topology config for 2CS 1GB.

### CODE REVIEW

**Comment by afaerber** [comment]
I've successfully booted into U-Boot with this, but mainline U-Boot shows 512 MiB of DRAM instead of expected 2 GiB - could that be a U-Boot issue, or is there an issue with the config or tools here?

**Comment by kostapr** [comment]
Doesn't commit 845f670be9cbed3d3561a8d20c99f23e1b866daf cover it?

**Comment by afaerber** [comment]
First of all, my report was from June 2018 and that commit is from November 2018, now we have November 2019. Second, this was about DDR3 whereas your commit is about DDR4 apparently. Haven't tried in a while - it's really sad to have a board that's completely unsupported...

**Comment by kostapr** [comment]
@afaerber I understand your feeling. But EspressoBin design is controlled by GlobalScale. It is out of Marvell hands. I was totally surprised to found that the new v7 design uses DDR4 and only supported by the manufacturer boot image. So I added this support due to Armbian team complains.

**Comment by MarSoft** [comment]
Not sure if it is of any interest, but on my ESPRESSObin v7 with 1GiB DDR4 DRAM the mainline U-Boot also shows only 512MiB (and crashes somewhere during loading). Probably it is related to @afaerber's 512MiB issue.

**Comment by kostapr** [comment]
DRAM size in u-boot is taken using SMC call to ATF. Half of installed DRAM may be indicator for bad topology configuration (1 CS instead of 2 CS) or wrong DRAM chip size per CS.
Current 1GB Espressobin v7 topology (#5) assumes single DDR chip select and 1GB DDR die on it.
However the manufacturer may switch to another DDR chips maintaining the same total DRAM size. For instance may use 512MB dies with 2 chip selects. In such case the topology should be changed to match the board configuration.
/*
 This file is the input for A3700 DDR porting tool,
 each item is one parameter for DDR topology, which will be parsed by
 DDR tool and generate DDR register list accordingly.
 Supported Marvell boards:
       DDR4 1CS : ESPERSSOBIN-DDR4 single K4A8G165WB-BCRC (1GB)
*/
#DDR4
ddr_type=1

#1CS
ddr_cs_mask=1

#DDR4_2400T
ddr_speedbin_index=11

#16BIT
ddr_bus_width_index=2

#8Gbits (1GB)
ddr_mem_size_index=4

**Comment by kostapr** [comment]
https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell/blob/A3700_utils-armada-18.12/tim/ddr/porting_guide.txt

**Comment by pali** [comment]
This pull request was superseded by new pull request https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell/pull/10 and was already merged into A3700_utils-armada-18.12-fixed branch by commit https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell/commit/096797908ddd69a679fd55595c41fc02809829a9

@kostapr @afaerber: So you can close this merge request now.

**Pull request closed without merging**
